### ISSUE TITLE
Links in Credits are not clickable

### ISSUE THREAD

**Issue by hubacekjakub** [jame581/Submarinened#1]
Cannot click on links in credits. This prevents me from checking more of your projects on azure :)

**Comment by jame581** [comment]
Thanks for report, bug was fixed in [commit 333871821 ](https://github.com/jame581/Submarinened/commit/333871821c79963b944c42e2c9ace2983dae4809)

**Comment by jame581** [comment]
There was mistake in communication, that's reason why I opened issue again. Fix is created a and PR linked.
